version: 2.1

orbs:
  node: circleci/node@5.1.0

workflows:
  test-and-release:
    jobs:
      - node/test:
          version: '19.6.0'
          pkg-manager: yarn
          command: |
            yarn release
