name: Release
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x]

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is running on a ${{ runner.os }} server hosted by GitHub"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with: 
          cmd: install

      - name: Lint
        uses: borales/actions-yarn@v4
        with: 
          cmd: lint:all

      - name: Build
        uses: borales/actions-yarn@v4
        with: 
          cmd: build

      - name: Release
        uses: borales/actions-yarn@v4
        with: 
          cmd: run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}